# Generated by Django 5.1.3 on 2024-12-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_userprofile_description_userprofile_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_business',
        ),
    ]
