# Generated by Django 5.1.3 on 2024-12-18 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='revisions',
            field=models.IntegerField(default=0, help_text='Number of revisions allowed. Use -1 for unlimited revisions.', validators=[django.core.validators.MinValueValidator(-1)]),
        ),
    ]
