# Generated by Django 5.1.3 on 2024-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0002_remove_offer_details_offerdetail_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.CharField(choices=[('Logo Design', 'Logo Design'), ('Visitenkarte', 'Visitenkarte'), ('Briefpapier', 'Briefpapier'), ('Flyer', 'Flyer')], default='Logo Design', max_length=50),
        ),
    ]
