# Generated by Django 5.1.3 on 2024-12-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offerdetail_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='features',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.ManyToManyField(to='offers_app.feature'),
        ),
    ]
