# Generated by Django 5.1.3 on 2024-12-07 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0007_alter_order_status'),
        ('user_auth_app', '0004_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_orders', to='user_auth_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to='user_auth_app.userprofile'),
        ),
    ]
