# Generated by Django 5.1.3 on 2024-12-07 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0011_delete_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
