# Generated by Django 5.1.3 on 2024-12-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0013_alter_offerdetail_revisions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='features',
            field=models.ManyToManyField(blank=True, to='offers_app.feature'),
        ),
    ]
