# Generated by Django 5.1.3 on 2024-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0014_alter_offerdetail_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
