# Generated by Django 5.1.3 on 2024-12-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0002_alter_review_business_user_alter_review_reviewer'),
        ('user_auth_app', '0004_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='business_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_for_business', to='user_auth_app.userprofile'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_by_user', to='user_auth_app.userprofile'),
        ),
    ]
